### ISSUE TITLE
Visual Studio compilation errors with Unity

### ISSUE THREAD

**Issue by slimshader** [Cysharp/UnitGenerator#26]
Hi,

when using with Unity (2021.3), it is no longer possible to debug with VS 2022 as it can't get past compilation errors related to UnitOf types. Surprisingly, I have 2 other generators (DefaultECS and VContainer) and those do not cause the issues. I've Added "C# Project Modifer" and added Roslyn Analyzers and still no luck. (again, interesting part is that 2 other generators cause no VS issues even without C# project modifier")

**Comment by hadashiA** [comment]
@slimshader Hi,
Sounds like a curios problem. but I could not reproduce it.
I created a project with Unity 2021.3.29f1 that included UnitGenerator.dl and Container.SourceGenerator.dll and both SourceGenerators worked.

Sorry but If the problem continues, could you please provide a detailed error log (and if possible a reproducible project)? 
Thanks.

**Comment by slimshader** [comment]
@hadashiA it is not about generators not working, it is about visual studio not seeing generated files, which results in errors (in Visual Studio) which blocks from possibility of attaching a debugger.

**Comment by hadashiA** [comment]
@slimshader 
hmm, I tried again with Visual Studio 2022 (win) + Unity 2021.3.

- But no compile errors were detected.
  - One possibility could be that your generate result code contains compile errors.
  - Since UnitGenerator does not perform detailed checks before generation, you need to check the generated code for errors.
      - For example, `[UnitOf(typeof(DateTime), UnitGenerateOptions.ArithmeticOperator)]` generates compilation errors.
      - You will probably get an error message, so try changing the UnitOf options, etc.
- Also, you are right, I did not see the generated code in Visual Studio's Solution Explorer on my end.
  - However, I think this is not a problem with UnitGenerator.dll itself.
  - Other SourceGenerators has similar problems.
  - When I tried the same project in my environment, the generated code showed up.

It is difficult to investigate further here.
If you still suspect a UnitGenerator problem, please reopen with a reproduced project :)
